const defaults={profile:{people:2,days:3,children:false,olderAdults:false,pets:false,medications:false,mobility:false},checked:{},plan:{homeMeeting:"",neighborhoodMeeting:"",outOfAreaContact:"",evacuationRoute:"",shelterNotes:"",responsibilities:""}};
const base=[['water','Water & food','Stored drinking water'],['food','Water & food','At least 3 days of nonperishable food'],['opener','Water & food','Manual can opener'],['radio','Information','Battery or hand-crank radio','Include a NOAA Weather Radio if available.'],['alerts','Information','Local alerts enabled','Know which local agencies issue warnings where you live.'],['light','Home safety','Flashlights and spare batteries'],['firstaid','Home safety','First-aid kit'],['whistle','Home safety','Whistle for signaling'],['sanitation','Home safety','Sanitation supplies and trash bags'],['cash','Practical essentials','Small amount of cash'],['chargers','Practical essentials','Backup phone charging'],['documents','Practical essentials','Protected copies of key documents'],['maps','Practical essentials','Local paper map']];
const extras={children:['children','Household needs','Child-specific food, comfort, and care items'],olderAdults:['older','Household needs','Glasses, hearing-aid supplies, and support contacts'],pets:['pets','Household needs','Pet food, water, carrier, leash, and records'],medications:['meds','Household needs','Medication plan and current list','Ask a clinician or pharmacist how to prepare safely.'],mobility:['access','Household needs','Backup plan for mobility or powered medical equipment']};
const load=(key,fallback)=>{try{return JSON.parse(localStorage.getItem(key))||fallback}catch{return fallback}};const save=(key,value)=>{try{localStorage.setItem(key,JSON.stringify(value))}catch{}};
let profile=load('readyNeighbor.profile',defaults.profile),checked=load('readyNeighbor.checked',{}),plan=load('readyNeighbor.plan',defaults.plan);
const items=()=>base.concat(Object.keys(extras).filter(k=>profile[k]).map(k=>extras[k]));
function render(){document.querySelector('#people').value=profile.people;document.querySelector('#days').value=profile.days;document.querySelectorAll('[data-profile]').forEach(x=>x.checked=!!profile[x.dataset.profile]);const list=items(),cats=[...new Set(list.map(x=>x[1]))],root=document.querySelector('#check-groups');root.innerHTML=cats.map(c=>`<div class="check-group"><h3>${c}</h3>${list.filter(x=>x[1]===c).map(x=>`<label class="check-item"><input type="checkbox" data-item="${x[0]}" ${checked[x[0]]?'checked':''}><span class="custom-check" aria-hidden="true">✓</span><span><strong>${x[2]}</strong>${x[3]?`<small>${x[3]}</small>`:''}</span></label>`).join('')}</div>`).join('');root.querySelectorAll('[data-item]').forEach(x=>x.addEventListener('change',()=>{checked[x.dataset.item]=x.checked;save('readyNeighbor.checked',checked);updateProgress()}));document.querySelector('#water-total').textContent=`${profile.people*profile.days} gallons`;document.querySelector('#water-detail').textContent=`${profile.people} ${profile.people===1?'person':'people'} × ${profile.days} days`;updateProgress()}
function updateProgress(){const list=items(),done=list.filter(x=>checked[x[0]]).length,pct=Math.round(done/list.length*100);document.querySelector('#progress-label').textContent=`${done} of ${list.length} ready`;document.querySelector('#progress-percent').textContent=`${pct}% complete`;const bar=document.querySelector('.progress-track');bar.setAttribute('aria-valuenow',pct);bar.querySelector('span').style.width=`${pct}%`}
document.querySelectorAll('[data-profile]').forEach(x=>x.addEventListener('change',()=>{profile[x.dataset.profile]=x.checked;save('readyNeighbor.profile',profile);render()}));['people','days'].forEach(id=>document.querySelector(`#${id}`).addEventListener('change',e=>{const min=id==='people'?1:3,max=id==='people'?20:14;profile[id]=Math.min(max,Math.max(min,Number(e.target.value)||min));save('readyNeighbor.profile',profile);render()}));
document.querySelectorAll('[data-plan]').forEach(x=>{x.value=plan[x.dataset.plan]||'';x.addEventListener('input',()=>{plan[x.dataset.plan]=x.value;save('readyNeighbor.plan',plan);const s=document.querySelector('.save-status');s.textContent='Saved on this device';clearTimeout(window.saveTimer);window.saveTimer=setTimeout(()=>s.textContent='',1800)})});
document.querySelector('.plan-form').addEventListener('submit',e=>e.preventDefault());document.querySelector('#clear-plan').addEventListener('click',()=>{if(confirm('Clear the plan saved in this browser?')){plan={...defaults.plan};save('readyNeighbor.plan',plan);document.querySelectorAll('[data-plan]').forEach(x=>x.value='')}});document.querySelectorAll('[data-print]').forEach(x=>x.addEventListener('click',()=>print()));
const menu=document.querySelector('.menu-button'),nav=document.querySelector('.nav');menu.addEventListener('click',()=>{const open=!nav.classList.contains('open');nav.classList.toggle('open',open);menu.setAttribute('aria-expanded',open);menu.querySelector('[aria-hidden]').textContent=open?'×':'☰';menu.querySelector('.sr-only').textContent=open?'Close menu':'Open menu'});nav.querySelectorAll('a').forEach(a=>a.addEventListener('click',()=>{nav.classList.remove('open');menu.setAttribute('aria-expanded','false')}));
render();
